spring:
  datasource:
    password: demopassword
    url: jdbc:postgresql://database-3.cwukqvldiavm.us-east-1.rds.amazonaws.com:5432/OnlineStore
    username: vadym
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5000
springdoc:
  swagger-ui:
    path: /swagger